# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LazyLoadInImages' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LazyLoadInImages

  # Yoga
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  pod 'React', path: '../node_modules/react-native', subspecs: [
  'ART',
]

  target 'LazyLoadInImagesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LazyLoadInImages-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LazyLoadInImages-tvOS

  target 'LazyLoadInImages-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
